# ==========================================================
# Inventario de servidores Linux
# Proyecto Final - CREATIC
# Módulo 5 - Automatización del Hardening
# ==========================================================

[linux_servers]

CR-APPSRV-02 ansible_connection=local
CR-DB-01 ansible_connection=local
